name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  bucket:
    required: true
    description: 'Name of Google Cloud Storage bucket to use.'
  filename:
    required: true
    description: 'Filename to use as a lock.'
    default: 'lock'
  timeout:
    required: true
    description: 'Timeout before acquiring the lock should fail.'
    default: '10m'

runs:
  using: 'node12'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'
